In [5]:
nums = list(range(5))
print(nums)
print(nums[:-1])
print(nums[-1:])

[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[4]


In [17]:
import numpy as np

In [18]:
a = np.array(list(range(5)))
print(a)
print(a[1:3])

[0 1 2 3 4]
[1 2]


In [19]:
b = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(b)
print(b[:,1])
print(b[-1])
print(b[-1,:])
print(b[-1, ...])
print(b[0:2, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
import tensorflow as tf
import numpy as np

In [ ]:
xy = np.loadtxt('./data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [55]:
x_data = [1,2,3,4]
y_data = [1,2,3,4]

In [56]:
W = 5

In [57]:
temp = []
temp.append(W)

for itr in range(100):
    sum = 0
    for i in range(len(x_data)):
        sum = sum + (x_data[i]*W - y_data[i])*x_data[i]
    average = sum / len(x_data)


    W = W - 0.1 * average
    temp.append(W)

In [58]:
for i in temp:
    print(i)

5
2.0
1.25
1.0625
1.015625
1.00390625
1.0009765625
1.000244140625
1.00006103515625
1.0000152587890625
1.0000038146972656
1.0000009536743164
1.000000238418579
1.0000000596046448
1.0000000149011612
1.0000000037252903
1.0000000009313226
1.0000000002328306
1.0000000000582077
1.000000000014552
1.000000000003638
1.0000000000009095
1.0000000000002274
1.0000000000000568
1.0000000000000142
1.0000000000000036
1.0000000000000009
1.0000000000000002
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
